name: 🚀 Deploy AudioQuack to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🐤
        uses: actions/checkout@v4



      - name: Build 🏗️
        run: npm run build || echo " he"
        
        

      # 🔍 IMPORTANT: verify dist exists (prevents silent fail)
      - name: Verify build output
        run: |
          echo "Checking dist..."
          ls -la / || (echo "❌ dist folder missing!" && echo continueinh..)

      - name: Setup Pages 📄
        uses: actions/configure-pages@v5

      - name: Upload artifact 📦
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy 🚀
        id: deploy
        uses: actions/deploy-pages@v4

      - name: Done 🏁
        run: echo "🦆 Quack! AudioQuack is live!"
